### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by ccarstens** [Kinrany/vue-p5#7]
Hi @Kinrany,

first of all, thank you very much for creating a vue-p5, I'm excited to use it!

At the moment when I try to setup a small example I get the following error:
![bildschirmfoto 2018-06-23 um 14 49 15](https://user-images.githubusercontent.com/29205799/41809844-b5b0b0f2-76f4-11e8-9351-1583d8cb001c.png)

![bildschirmfoto 2018-06-23 um 15 08 15](https://user-images.githubusercontent.com/29205799/41810011-49ecdcee-76f7-11e8-9c7c-634f4783233d.png)

I set up an empty vue-cli project and included your example component from your repo vue-p5-example.

Can you reproduce the issue on your end?

Thank you!
ccarstens

**Comment by Kinrany** [comment]
Hey @ccarstens, thank you for the report! I think I see the problem, should be able to fix it in a couple of days.

In the meantime you could try using version `0.4.3`: https://github.com/Kinrany/vue-p5/tree/v0.4.3

Should work fine, since that's the version I used the last time I updated `vue-p5-example`.

The main difference between versions is that `0.5.x` use lowercase instead of kebab-case for event names.  
`0.4.x` are also missing some p5 events, check the `event_names` variable in `p5.vue`: https://github.com/Kinrany/vue-p5/blob/v0.4.3/src/p5.vue

**Comment by ccarstens** [comment]
Hey @Kinrany 
thank you for the quick reply.
I tried `0.4.3` before but accidentally installed `0.4.4`.
´0.4.3` works as expected, thank you very much!
best
ccarstens

**Comment by Kinrany** [comment]
I published a fixed version as `0.6.0-rc1` and updated `vue-p5-example`.

Did you get an error with `0.4.4` too? They should be exactly the same, but there could be another bug.

I'll close this issue for now to mark it as resolved, please let me know if there are other problems. And feel free to share your project when it's done :)
